{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Not using LLM\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   0%|          | 0/333 [00:00<?, ?it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7DEJNPU.info\\wallhaven-v9gp9l.jpg (1200×1621).png:\n",
      "Exception: Failed to load image: P:\\datasets\\wallhaven\\processed\\LV0Z7L7DEJNPU.info\\wallhaven-v9gp9l.jpg (1200×1621).png\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 75, in _process_raster\n",
      "    raise ValueError(f\"Failed to load image: {image_path}\")\n",
      "ValueError: Failed to load image: P:\\datasets\\wallhaven\\processed\\LV0Z7L7DEJNPU.info\\wallhaven-v9gp9l.jpg (1200×1621).png\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7DJI9HP.info\\wallhaven-gpqypd.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7CNDZO4.info\\wallhaven (2385).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7C8LUBN.info\\wallhaven (2386).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7DVZGYH.info\\wallhaven (2389).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7CJ5N7O.info\\wallhaven (2388).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7C4N1VO.info\\wallhaven (2383).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7CD9ZM3.info\\wallhaven (2384).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7CMMNKN.info\\wallhaven (2387).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   0%|          | 1/333 [00:00<02:13,  2.49it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7DPGIYO.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7BNO6IV.info\\wallhaven (2378).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7BV8BPT.info\\wallhaven (2379).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7CH9KCR.info\\wallhaven (2382).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7C6J9NM.info\\wallhaven (2381).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7BHE1NC.info\\wallhaven (2376).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7BBZRRC.info\\wallhaven (2380).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7BPUBP3.info\\wallhaven (2377).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   1%|          | 2/333 [00:00<02:43,  2.03it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7B4ZL73.info\\wallhaven (2375).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7BKIMMT.info\\wallhaven (2373).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7BFGA6C.info\\wallhaven (2374).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7AUSI0U.info\\wallhaven (2371).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YS26F9AR6V.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7AHHXJD.info\\wallhaven (2370).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YS0NJWN7GE.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YRPV5GFLEF.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7A7LZ7Q.info\\wallhaven (2369).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YRSXZD748J.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YROCHDX7OO.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0Z7L7BVVO7F.info\\wallhaven (2372).jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   1%|          | 3/333 [00:01<04:00,  1.37it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YRRFPS8RDR.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YRBYO4ONKV.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YR5SU9G9EM.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YRGLC27XXN.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YRI5OT7LVV.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YRL8ZQ94Z3.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YRF38M8NA9.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YR2OIBITU7.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YR49IX8GER.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YRJP9YZ8ND.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   1%|          | 4/333 [00:02<04:02,  1.36it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YR7DB57A2C.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YQPL5FMGLR.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YQXA9OJJN3.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YQHV51UEPC.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YQGBG61M4F.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YQJEDCHXS4.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YQESO51XKC.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YQVRXGJ8XG.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YQL0GBP251.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YQSO96FNFJ.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   2%|▏         | 5/333 [00:04<06:50,  1.25s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YQYUEVJ984.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YPSI4LBUAK.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YQ5KE3A99H.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YPZC0F2RLI.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YQ3ZNV7A4M.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YPNRAMMVOE.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YPJ4NFDTMJ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YPMA9D1FNK.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YPTYCP50M3.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YPKP1U59K1.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   2%|▏         | 6/333 [00:05<05:35,  1.03s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YQ72ODBF7J.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YOW1U4FY17.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YPHLYXAJZC.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YP6TN2V9E1.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YOZ3C0WN2W.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YPD1JFOJ8R.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YOSWY6QOMA.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YP26XLJHLA.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YP0MQ59IG5.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YP8CEOOFZE.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   2%|▏         | 7/333 [00:06<05:28,  1.01s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YPBFJH9TFQ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YOAEUEBX11.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YOI3UKZP49.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YO8VBZ4QMD.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YOMR14B8GM.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YO5UQ5O2R7.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YO145ZQ0D6.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YO48RUL7K5.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YO7DD311HT.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   2%|▏         | 8/333 [00:06<04:19,  1.25it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YOC0WAYC8T.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YO2OSITET9.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YNFJ6IVU2Y.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YNLR35NF16.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YNY1TFT172.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YNQC8RS95R.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YNK7FDWZBY.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YNWICBU05Z.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YNTETBJ96O.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YNIT63H38D.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YNUZJJJID1.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   3%|▎         | 9/333 [00:07<03:37,  1.49it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YNOSHOAOWI.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YN1N69XHQG.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YMVJ9SI7MV.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YN4QW1S6MD.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YNCGCXHNNR.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YMWZXZ28LW.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YMYJASZ79G.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YN05RRIGFL.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YMTY7Y1G2F.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   3%|▎         | 10/333 [00:07<03:48,  1.41it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YN37RYDBIG.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YN7U7FI9Y3.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YM7KN69P8U.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YM4HFUK2HY.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YMQTPJK88O.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YM605U43ZZ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YM2Z6CGDI2.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YMSDS4G6ZO.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YMJW2MF1IN.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YMFARCX5ZQ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YLZUVSXX4H.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   3%|▎         | 11/333 [00:08<03:49,  1.40it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YMICYM9WGE.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YLQM487OYV.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YLJMQCZF4T.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YLGJZQ29SG.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YLYB4QOFT3.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YLTPN5TURD.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YLF2L0MP08.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YLS4XNJVO0.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YLWS5B3ISF.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   4%|▎         | 12/333 [00:09<03:31,  1.52it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YLV80JHW52.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YLNGQTJS0B.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YLDGIBIL7H.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YLBX5JO7J4.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YL2QL6ZWT0.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YL15E4Y3GJ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YKWGKAQAXU.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YKY1S12HF1.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YL7A4ZBCBP.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YL470GVG3K.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YKZJSM1L7J.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   4%|▍         | 13/333 [00:09<03:05,  1.72it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YKUY6IX776.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YKTFDS4SLE.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YKAVKTD2RH.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YKFIARU7FY.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YK9DGP2WJ6.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YKK4IH4CZ1.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YKRZJN0NOS.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YKCEF2DMW3.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YKRJSMOF5Y.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YK7SDB66D7.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   4%|▍         | 14/333 [00:10<03:03,  1.74it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YKR81MJ0X8.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YK36VX0I9K.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YJP98EEKH2.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YJHK1HB5ZL.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YJKOHC73PU.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YJSEA88S2N.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YJTVSGK2P8.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YJQTD57DOQ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YK03BPE670.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   5%|▍         | 15/333 [00:10<03:05,  1.71it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YK4OK6KQ25.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YJVGDLD3DQ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YJ8AMZ9HGS.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YIZ24KP9Y3.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YIVXWQP62Z.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YIRCMZ0G4C.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YJ25KPNJ0E.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YIUF4WUE43.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YJ588C58KE.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YISW1IZ5RT.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   5%|▍         | 16/333 [00:11<03:20,  1.58it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YIXIX8TB1D.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YJCXBA9YI0.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YIO8C5BSMJ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YIPUJDGS1L.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YIJMLHJ2S6.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YIL4RW8DAO.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YIMOPYBALO.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YIEYRV879R.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YI8SX62FAJ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YIACFQBH9V.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YI79Z4XNI4.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   5%|▌         | 17/333 [00:12<03:11,  1.65it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YIGKCOZMDV.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YI140Y4WQZ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YI45OUZG5N.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YHUXXR7CXV.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YHRV4BGLU2.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YHQ9XRYJ03.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YI2NQSQNLW.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YHN8U4HZTC.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YHY0C6AMJI.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YHTEEGET5G.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   5%|▌         | 18/333 [00:12<02:56,  1.78it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YHWIDSJ3AE.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YHDXKM5B03.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YHFHDE3BQP.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YHIJPAUQ71.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YH8K5RSFRI.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YH2DCL8SXI.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YHCE7QEC6B.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YHK6WP2MC9.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   6%|▌         | 19/333 [00:13<03:09,  1.66it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YH70K5O30I.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YH5I9A0FFG.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YH3X3RJBW4.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YGMXQM3U5Y.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YGZCB122GP.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YH0SZDSF2F.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YGQ2JY458W.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YGLDH1W1L6.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YGT38NNEDW.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YGOHY190D3.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YGW6NUVCV5.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   6%|▌         | 20/333 [00:13<03:16,  1.59it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YGXSBID3EC.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YGUNCJ8MKY.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YFV6SGFPJ4.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YGAKXN7CRI.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YG1B6EJEKI.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YFTLZSX87B.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YG7J6H5C78.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YFY9DQ8UJU.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YGC5LRT0UX.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YG4LX85YRA.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YG5YCAXYSN.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   6%|▋         | 21/333 [00:14<03:17,  1.58it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YG2UYWPNB5.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YFE65E2C2G.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YF80SFO1CC.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YF9L4WKOEI.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YFHS1W0D6V.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YFCN7IUTBS.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YFKCOPNJ86.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YFNFZMFNBK.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   7%|▋         | 22/333 [00:14<02:52,  1.80it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YFOYNK0RBM.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YFFQC5K1E2.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YFISKWLTUM.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YF1TSB6139.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YENY555A6P.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YEXB0RN2L1.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   7%|▋         | 23/333 [00:15<02:21,  2.19it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YEPJ7F9OTL.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YESLHB735Y.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YEVWZXO1LC.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YF4X5CD0AH.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YEKUU6NIH9.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YEZ0SGXGTL.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YEU3G12OG6.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YEBLJEHI4P.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YE5FH44J7P.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YEAE8BT32Q.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YEJB1489MZ.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YED5LKK7RQ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YEEP0H8BSW.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YEG7XODMXY.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YE1L3FKELK.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   7%|▋         | 24/333 [00:15<02:38,  1.95it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YE70V8C5RH.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YE8JHCZI5Y.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YE013DBLK9.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YDX1MTCI0A.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YDEF9YCA0M.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YDJ3DTDDZW.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YDP7QP8L8H.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YDVDXV5CNR.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YDM4M3NMP4.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YDQRAYMODL.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   8%|▊         | 25/333 [00:17<05:06,  1.00it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YDHKZAIKTI.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YDKS837MYL.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YDCUSRE5Z6.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YD3NXFP2F1.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YD6PZLAFTM.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YCTM08RIEG.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YD9SEQKBN8.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YD56NRPG3Q.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YCWPTKCRK8.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YCV4BXD5UR.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YD88BZ96GV.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   8%|▊         | 26/333 [00:18<04:49,  1.06it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YD1B5GMYPP.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YCS2L6JHOI.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YCCMS9V0LL.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YCQHWSDPXH.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YCIRK9R0M3.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YCFQBD4DXW.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YCB318MNGP.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YC9JJ62ZF5.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YCNEQU2GO1.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YC7ZX6OJRJ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YCOYE5X0BK.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   8%|▊         | 27/333 [00:19<04:03,  1.25it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YC2KLW4OFW.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XVS6N8990Y.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YC3E5JHHZ5.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XVZXE14LVR.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XVYBGV4S4H.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XVV9M9DKCZ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XVQQLDM59E.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XVWTMHGO9D.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YC4VIYYQXM.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   8%|▊         | 28/333 [00:19<03:34,  1.42it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0YC6H1ILQV2.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XVLZTU4RSW.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XV835PBTVH.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XVFUAK7YBO.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XVEGSJOJ5L.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XVP38I2PFH.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XVNK6DAFVB.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XVB69Q3KXO.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   9%|▊         | 29/333 [00:20<02:58,  1.71it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XV9MMV9YJM.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XVIX1W0N6R.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XVKHFIC5XD.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XV0H0NN9M3.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XUGC033XS4.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XURB3C054E.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XUXCA3BHPO.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XUUGCA4QC0.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XUO1I0OTCZ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XUVQQV1DYU.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XUPL5M5RDS.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XV3GBI8633.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   9%|▉         | 30/333 [00:20<02:55,  1.73it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XUSOW9DW47.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XU5JGAZC5G.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XU2IHM0TG1.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XUBQMPXKF2.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XTU02MRHRY.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XUES7FCJ28.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XU8MQUPL9J.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XU0WLTEC3X.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:   9%|▉         | 31/333 [00:20<02:36,  1.93it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XUA5ILQR5U.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XTXU2W8C7W.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XU7314OCWA.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XTBH93QHSW.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XTM868EY0H.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XTCYB99GLQ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XTJ57FLUWQ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XTEIQRHJMV.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XTKQLA05ZH.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XTNRVFTOGK.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XTRTDE1A4T.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XT9VV5EAVK.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:  10%|▉         | 32/333 [00:21<02:39,  1.89it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XTQCYK03UR.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XT3QTVK9CU.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XSTWCVTUP6.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XSZ33ZJ1Q6.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XSQMOZLTLS.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XT59CSRXJ0.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XT6TA5TKDO.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XT8FIL3DPF.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XSVHLGQUPR.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XSP1QH35JE.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:  10%|▉         | 33/333 [00:22<02:37,  1.91it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XT266JKICK.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XSLYOXK5GL.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XS9M8EHJM4.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XSFSU8DTUM.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XS4ZUKQJDT.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XS82YKHOVU.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XSNIHS3XX9.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XSHC6FLJUO.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XSB5RW1R6A.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XSIVKVD5Q6.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:  10%|█         | 34/333 [00:23<03:27,  1.44it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XSE8M2P2JM.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XRVRPEZ6KB.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XRU721HZW6.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XRX9SSTWQH.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XS0GRQZT4P.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XRERQR5QT3.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XRYTGU3XSQ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XS1WOWUWOM.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XRJDRUB4UE.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XRHVTE028L.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:  11%|█         | 35/333 [00:23<03:17,  1.51it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XRMIMMV3G7.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XR0QMWXA8C.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XQT5HSK2XC.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XQXKPWHO96.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XQUOU16PYJ.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XR2BMZOKWD.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XRD7KEU1H5.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XRA4HZGILJ.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XR5C5COQWT.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XQZCYFE6Z2.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:  11%|█         | 36/333 [00:24<03:29,  1.42it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XR6TGE1M1A.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XQIDCNC2BM.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XQCAWW8FN6.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XQAMNM1UXH.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XQQ426SGF1.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XQJVFLO0R9.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XQF96ZSFTL.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XQMZ1GMFDU.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XQRLJDO8WX.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n",
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XQOIASLVK5.info\\wallhaven.png:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Processing image batches:  11%|█         | 36/333 [00:25<03:26,  1.44it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing image P:\\datasets\\wallhaven\\processed\\LV0XQDQA9XXE1.info\\wallhaven.jpg:\n",
      "Exception: No module named 'image_utils'\n",
      "Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py\", line 118, in _process_raster\n",
      "    import image_utils\n",
      "ModuleNotFoundError: No module named 'image_utils'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[1], line 7\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m      6\u001b[0m     start_time \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mtime()  \u001b[38;5;66;03m# Start timer for entire process\u001b[39;00m\n\u001b[1;32m----> 7\u001b[0m     \u001b[43mio_utils\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mextract_EaglePack_and_process\u001b[49m\u001b[43m(\u001b[49m\u001b[43mconfig\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43minput_path\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m      8\u001b[0m     end_time \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mtime()  \u001b[38;5;66;03m# End timer for entire process\u001b[39;00m\n\u001b[0;32m      9\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mTotal processing time: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mend_time\u001b[38;5;250m \u001b[39m\u001b[38;5;241m-\u001b[39m\u001b[38;5;250m \u001b[39mstart_time\u001b[38;5;132;01m:\u001b[39;00m\u001b[38;5;124m.2f\u001b[39m\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m seconds\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[1;32mc:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\io_utils.py:41\u001b[0m, in \u001b[0;36mextract_EaglePack_and_process\u001b[1;34m(eaglepacks_path)\u001b[0m\n\u001b[0;32m     39\u001b[0m     aug_type, aug_value, aug_percentage \u001b[38;5;241m=\u001b[39m augment\n\u001b[0;32m     40\u001b[0m     \u001b[38;5;66;03m# With augmentation\u001b[39;00m\n\u001b[1;32m---> 41\u001b[0m     \u001b[43mfolder_utils\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmake_folders_recursively\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m     42\u001b[0m \u001b[43m        \u001b[49m\u001b[43mprocessed_dir\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mfolders\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mimages\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mbasefolder\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mprocessed_dir\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcounter\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mlock\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     43\u001b[0m \u001b[43m        \u001b[49m\u001b[43maugment\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43maug_type\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43maug_value\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43maug_percentage\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     44\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m           \n\u001b[0;32m     45\u001b[0m end_time \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mtime()  \u001b[38;5;66;03m# End timer\u001b[39;00m\n\u001b[0;32m     46\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mTime taken for augmentation \u001b[39m\u001b[38;5;132;01m{\u001b[39;00maugment\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mend_time\u001b[38;5;250m \u001b[39m\u001b[38;5;241m-\u001b[39m\u001b[38;5;250m \u001b[39mstart_time\u001b[38;5;132;01m:\u001b[39;00m\u001b[38;5;124m.2f\u001b[39m\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m seconds\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[1;32mc:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\folder_utils.py:46\u001b[0m, in \u001b[0;36mmake_folders_recursively\u001b[1;34m(root, folder, images, basefolder, processed_dir, counter, lock, augment)\u001b[0m\n\u001b[0;32m     41\u001b[0m     image_processing_tasks\u001b[38;5;241m.\u001b[39mappend(\n\u001b[0;32m     42\u001b[0m         delayed(api_instance\u001b[38;5;241m.\u001b[39mprocess_image_batch)(images_batch, current_path, basefolder, image_paths_batch, counter, lock, augment)\n\u001b[0;32m     43\u001b[0m     )\n\u001b[0;32m     45\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m image_processing_tasks:\n\u001b[1;32m---> 46\u001b[0m     \u001b[43mParallel\u001b[49m\u001b[43m(\u001b[49m\u001b[43mn_jobs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mconfig\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnumber_of_jobs\u001b[49m\u001b[43m)\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m     47\u001b[0m \u001b[43m        \u001b[49m\u001b[43mtqdm\u001b[49m\u001b[43m(\u001b[49m\u001b[43mimage_processing_tasks\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdesc\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mProcessing image batches\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[0;32m     48\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     50\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m child \u001b[38;5;129;01min\u001b[39;00m folder\u001b[38;5;241m.\u001b[39mget(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mchildren\u001b[39m\u001b[38;5;124m\"\u001b[39m, []):\n\u001b[0;32m     51\u001b[0m     make_folders_recursively(current_path, child, images, basefolder, processed_dir, counter, lock, augment\u001b[38;5;241m=\u001b[39maugment)\n",
      "File \u001b[1;32mg:\\anaconda3\\envs\\aes\\lib\\site-packages\\joblib\\parallel.py:1863\u001b[0m, in \u001b[0;36mParallel.__call__\u001b[1;34m(self, iterable)\u001b[0m\n\u001b[0;32m   1861\u001b[0m     output \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_get_sequential_output(iterable)\n\u001b[0;32m   1862\u001b[0m     \u001b[38;5;28mnext\u001b[39m(output)\n\u001b[1;32m-> 1863\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m output \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mreturn_generator \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;28;43mlist\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43moutput\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   1865\u001b[0m \u001b[38;5;66;03m# Let's create an ID that uniquely identifies the current call. If the\u001b[39;00m\n\u001b[0;32m   1866\u001b[0m \u001b[38;5;66;03m# call is interrupted early and that the same instance is immediately\u001b[39;00m\n\u001b[0;32m   1867\u001b[0m \u001b[38;5;66;03m# re-used, this id will be used to prevent workers that were\u001b[39;00m\n\u001b[0;32m   1868\u001b[0m \u001b[38;5;66;03m# concurrently finalizing a task from the previous call to run the\u001b[39;00m\n\u001b[0;32m   1869\u001b[0m \u001b[38;5;66;03m# callback.\u001b[39;00m\n\u001b[0;32m   1870\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_lock:\n",
      "File \u001b[1;32mg:\\anaconda3\\envs\\aes\\lib\\site-packages\\joblib\\parallel.py:1792\u001b[0m, in \u001b[0;36mParallel._get_sequential_output\u001b[1;34m(self, iterable)\u001b[0m\n\u001b[0;32m   1790\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mn_dispatched_batches \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;241m1\u001b[39m\n\u001b[0;32m   1791\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mn_dispatched_tasks \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;241m1\u001b[39m\n\u001b[1;32m-> 1792\u001b[0m res \u001b[38;5;241m=\u001b[39m func(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[0;32m   1793\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mn_completed_tasks \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;241m1\u001b[39m\n\u001b[0;32m   1794\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mprint_progress()\n",
      "File \u001b[1;32mc:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py:24\u001b[0m, in \u001b[0;36mProcessImageAPI.process_image_batch\u001b[1;34m(self, images_batch, folder_path, basefolder, image_paths_batch, counter, lock, augment)\u001b[0m\n\u001b[0;32m     23\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mprocess_image_batch\u001b[39m(\u001b[38;5;28mself\u001b[39m, images_batch, folder_path, basefolder, image_paths_batch, counter, lock, augment\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m):\n\u001b[1;32m---> 24\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mprocess_images\u001b[49m\u001b[43m(\u001b[49m\u001b[43mimages_batch\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mfolder_path\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mbasefolder\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mimage_paths_batch\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcounter\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mlock\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mrename\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrename\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43maugment\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43maugment\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\Users\\Daniel\\CodingProjects\\eagle_tools\\utils\\process_image_API.py:148\u001b[0m, in \u001b[0;36mProcessImageAPI.process_images\u001b[1;34m(self, images, folder_path, basefolder, image_paths, counter, lock, rename, augment)\u001b[0m\n\u001b[0;32m    145\u001b[0m     futures\u001b[38;5;241m.\u001b[39mappend(executor\u001b[38;5;241m.\u001b[39msubmit(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mprocess_image, image, folder_path, basefolder, image_path, count, rename, augment))\n\u001b[0;32m    147\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m future \u001b[38;5;129;01min\u001b[39;00m futures:\n\u001b[1;32m--> 148\u001b[0m     \u001b[43mfuture\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mresult\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mg:\\anaconda3\\envs\\aes\\lib\\concurrent\\futures\\_base.py:453\u001b[0m, in \u001b[0;36mFuture.result\u001b[1;34m(self, timeout)\u001b[0m\n\u001b[0;32m    450\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_state \u001b[38;5;241m==\u001b[39m FINISHED:\n\u001b[0;32m    451\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__get_result()\n\u001b[1;32m--> 453\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_condition\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwait\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    455\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_state \u001b[38;5;129;01min\u001b[39;00m [CANCELLED, CANCELLED_AND_NOTIFIED]:\n\u001b[0;32m    456\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m CancelledError()\n",
      "File \u001b[1;32mg:\\anaconda3\\envs\\aes\\lib\\threading.py:320\u001b[0m, in \u001b[0;36mCondition.wait\u001b[1;34m(self, timeout)\u001b[0m\n\u001b[0;32m    318\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:    \u001b[38;5;66;03m# restore state no matter what (e.g., KeyboardInterrupt)\u001b[39;00m\n\u001b[0;32m    319\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m timeout \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m--> 320\u001b[0m         \u001b[43mwaiter\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43macquire\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    321\u001b[0m         gotit \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m\n\u001b[0;32m    322\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "import time\n",
    "import utils.config as config\n",
    "import utils.io_utils as io_utils\n",
    "if __name__ == \"__main__\":\n",
    "    try:\n",
    "        start_time = time.time()  # Start timer for entire process\n",
    "        io_utils.extract_EaglePack_and_process(config.input_path)\n",
    "        end_time = time.time()  # End timer for entire process\n",
    "        print(f\"Total processing time: {end_time - start_time:.2f} seconds\")\n",
    "    finally:\n",
    "        if config.use_LLM:\n",
    "            config.llm_processor.stop()\n",
    "    print(\"Processing completed\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
